BookingSystem/Controllers/TableController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BookingSystem.DAL;
using BookingSystem.Models;

namespace BookingSystem.Controllers
{
    public class TableController : Controller
    {
        private BookingContext db = new BookingContext();

        // GET: Table
        public ActionResult Index()
        {
            return View(db.Tables.ToList());
        }

        // GET: Table/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TableModel tableModel = db.Tables.Find(id);
            if (tableModel == null)
            {
                return HttpNotFound();
            }
            return View(tableModel);
        }

        // GET: Table/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Table/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TableId,TableNumber,TableCapacity")] TableModel tableModel)
        {
            if (ModelState.IsValid)
            {
                db.Tables.Add(tableModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tableModel);
        }

        // GET: Table/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TableModel tableModel = db.Tables.Find(id);
            if (tableModel == null)
            {
                return HttpNotFound();
            }
            return View(tableModel);
        }

        // POST: Table/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TableId,TableNumber,TableCapacity")] TableModel tableModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tableModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tableModel);
        }

        // GET: Table/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TableModel tableModel = db.Tables.Find(id);
            if (tableModel == null)
            {
                return HttpNotFound();
            }
            return View(tableModel);
        }

        // POST: Table/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TableModel tableModel = db.Tables.Find(id);
            db.Tables.Remove(tableModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BookingSystem/Views/Table/Create.cshtml
@model BookingSystem.Models.TableModel

@{
    ViewBag.Title = "Create Table";
}
<br />
<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <p class="lead">Please enter table details</p>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TableNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TableNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TableNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TableCapacity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TableCapacity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TableCapacity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BookingSystem/Views/Table/Delete.cshtml
@model BookingSystem.Models.TableModel

@{
    ViewBag.Title = "Delete Table";
}
<br />
<h2>Delete</h2>

<p class="lead">Are you sure you want to delete this table?</p>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TableNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TableNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TableCapacity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TableCapacity)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BookingSystem/Views/Table/Details.cshtml
@model BookingSystem.Models.TableModel

@{
    ViewBag.Title = "Table Details";
}
<br />
<h2>Details</h2>

<div>
    <p class="lead">List of full table details</p>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TableNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TableNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TableCapacity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TableCapacity)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.TableId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

BookingSystem/Views/Table/Edit.cshtml
@model BookingSystem.Models.TableModel

@{
    ViewBag.Title = "Edit Table";
}
<br />
<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <p class="lead">Please enter new table details</p>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TableId)

        <div class="form-group">
            @Html.LabelFor(model => model.TableNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TableNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TableNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TableCapacity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TableCapacity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TableCapacity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BookingSystem/Views/Table/Index.cshtml
@model IEnumerable<BookingSystem.Models.TableModel>

@{
    ViewBag.Title = "Tables";
}
<br />
<h2>Tables</h2>
<div class="row">
    <div class="col-md-6">
        <p class="lead">
            List of all tables in the restaurant
        </p>
    </div>
    <div class="col-md-6">
        <div class="float-right">
            <p>
                @Html.ActionLink("Create New", "Create", "Table", new { @class = "btn btn-outline-secondary" })
            </p>

        </div>
    </div>
</div>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TableNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TableCapacity)
        </th>
        <th class="text-right">
            Options
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.TableNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TableCapacity)
        </td>
        <td class="text-right">
            @Html.ActionLink("Edit", "Edit", new { id=item.TableId }, new { @class = "btn btn-sm btn-outline-secondary" })
            @Html.ActionLink("Details", "Details", new { id=item.TableId }, new { @class = "btn btn-sm btn-outline-secondary" })
            @Html.ActionLink("Delete", "Delete", new { id=item.TableId }, new { @class = "btn btn-sm btn-outline-secondary" })
        </td>
    </tr>
}

</table>